### ISSUE TITLE
Flag to display absolute paths

### ISSUE THREAD

**Issue by klauspost** [dominikh/go-simple#1]
For IntelliJ IDEA, it would be really nice to have an option to show the absolute path of files, since that would allow jump to line when using gosimple as an external task.

**Comment by dominikh** [comment]
Shouldn't IntelliJ interpret relative paths relative to the working directory of the process? How does it deal with golint?

**Comment by klauspost** [comment]
For Output Filters it only has an option for absolute path. [Output Filters](https://www.jetbrains.com/help/idea/2016.1/add-edit-filter-dialog-2.html?origin=old_help)

**Comment by dominikh** [comment]
That's quite a sad limitation of the editor. Do you know how it deals with golint, then, which has the same output?

**Comment by klauspost** [comment]
I cannot use click-to-jump-to line on golint output, so it doesn't work.

**Comment by dominikh** [comment]
I suggest you write a wrapper script around gosimple that turns the relative paths into absolute ones. IMO this is a flaw in the editor, and we shouldn't be adding flags to all the tools. `go vet`, `golint`, and a number of other tools will all have relative paths in their output, and most of those won't be adding a flag.

**Comment by klauspost** [comment]
Sounds like a good idea. Cheers.
