### ISSUE TITLE
Suggests raw string even when string contains backtick, which can't be contained in raw strings

### ISSUE THREAD

**Issue by ptman** [dominikh/go-simple#11]
The line in question is

https://github.com/revel/revel/blob/master/validators.go#L197

**Comment by dominikh** [comment]
IMO it would be more readable to use raw strings + string concatenation for the backtick, instead of needing to escape \ a dozen times.

**Comment by dominikh** [comment]
I'll close this issue. I stand by my earlier opinion, and there hasn't been any activity on this issue to convince me otherwise.

**Comment by dmitshur** [comment]
In general, I agree, but I can imagine a worse case scenario where the string value is:

`````` Go
var worstCase = regexp.MustCompile("```\\n")
``````

Would the suggestion still be valid then?

**Edit:** Perhaps so, because the above can still be rewritten more nicely... Do you agree?

``````
regexp.MustCompile("```" + `\n`)
``````

**Comment by dominikh** [comment]
The first version does look nicer imho. However, we'll cross that bridge when we come to it (i.e. when someone actually has that regular expression in their code.)

**Comment by dmitshur** [comment]
> However, we'll cross that bridge when we come to it (i.e. when someone actually has that regular expression in their code.)

That's exactly what I was thinking. 👍
