### ISSUE TITLE
Consider suggesting use of ioutil.Discard over make([]byte).

### ISSUE THREAD

**Issue by dmitshur** [dominikh/go-simple#13]
See https://github.com/shurcooL/vfsgen/pull/20.

The `gofmt -r` pattern is `io.ReadFull(r, make([]byte, n)) -> io.CopyN(ioutil.Discard, r, n)`.

The motivation is that ioutil.Discard uses a sync.Pool of byte slices, using which should in theory have better overall properties (less garbage generated). But I don't have any benchmarks to back that up.

**Comment by dmitshur** [comment]
I'm unsure if this is a great fit for `simple`. So far, it has suggestions for changes that you should have absolutely no reason not to do. Each one simplifies from a more complex/less idiomatic to an absolutely equivalent simpler alternative.

This change has tradeoffs. In some situations, one would want to use `io.CopyN(ioutil.Discard, r, n)` and in other specific situations, it's viable that `io.ReadFull(r, make([]byte, n))` can be used intentionally.

My suggestion is that if the user doesn't care, between those two, the `ioutil.Discard` is a better **default** to use. But I'm unsure it's a suitable simplification recommendation in all situations.

**Comment by dominikh** [comment]
I can't really think of a case where the first version would be preferable. Semantically, ioutil.Discard is a lot clearer to read. If there are values for `n` where the first version is considerably faster, I'd expect that code to appear in a loop or other hot path and work with a pre-allocated scratch space, not constantly make new slices. In that case, the rule wouldn't match.

**Comment by dmitshur** [comment]
> If there are values for `n` where the first version is considerably faster, I'd expect that code to appear in a loop or other hot path and work with a pre-allocated scratch space, not constantly make new slices.

I think I agree. If the first version is used for performance reasons, it's likely a custom optimized version of `io.ReadFull` would be used instead.

But still, if we're going to make suggestions to all of Go code in the world to replace the former with latter, I think we owe it to at least try an artificial benchmark and see how it compares. `sync.Pool` has non-trivial cost too (/cc @prashantv). Also, `io.CopyN` creates an `io.LimitedReader`, etc.

**Comment by dominikh** [comment]
Closing this issue. There are only about 100 hits for this pattern, and some of those hits shouldn't be rewritten. The gain isn't worth the complications (benchmarking, checking whether there is actually consensus on which version is better), so we won't implement it.
