### ISSUE TITLE
false positive on CockroachDB

### ISSUE THREAD

**Issue by tamird** [dominikh/go-simple#18]
Running against https://github.com/cockroachdb/cockroach/commit/ac79461eef6223544ee2d5ee49e908c94524767c

```
$ gosimple sql/sqlbase/table.go | grep -vF 'embedded.go'
sql/sqlbase/table.go:771:5: should omit nil check; len() for nil slices is defined as zero
```

Note that the code in question reads:

``` go
if directions != nil && len(directions) != len(valTypes) {
```

In other words, removing the nil check changes the semantics here.

**Comment by dmitshur** [comment]
Yep, that's a false positive since `len(valTypes)` can have a value that is not 0.
