### ISSUE TITLE
Go get fails

### ISSUE THREAD

**Issue by kirillDanshin** [dominikh/go-simple#2]
`can't load package: package github.com/dominikh/go-simple: code in directory /opt/go/gopath/src/github.com/dominikh/go-simple expects import "honnef.co/go/simple"`

**Comment by dmitshur** [comment]
You're using an incorrect import path.

See the [installation](https://github.com/dominikh/go-simple#installation) section in the README for the right one.

**Comment by kirillDanshin** [comment]
oh, you're right.
sorry.
