### ISSUE TITLE
TLS handshake timeout when trying to go get

### ISSUE THREAD

**Issue by ryboe** [dominikh/go-simple#22]
``` sh
$ go get -v honnef.co/go/staticcheck/cmd/staticcheck
Fetching https://honnef.co/go/staticcheck/cmd/staticcheck?go-get=1
https fetch failed: Get https://honnef.co/go/staticcheck/cmd/staticcheck?go-get=1: net/http: TLS handshake timeout
package honnef.co/go/staticcheck/cmd/staticcheck: unrecognized import path "honnef.co/go/staticcheck/cmd/staticcheck" (https fetch: Get https://honnef.co/go/staticcheck/cmd/staticcheck?go-get=1: net/http: TLS handshake timeout)
```

Every fourth or fifth time, the `go get` will succeed.

Would it be possible to switch to just using the GitHub URL instead of `honnef.co`?

EDIT: I just realize I posted the logs from go getting `staticcheck`. This issue still applies, though.

**Comment by gyuho** [comment]
Just facing this issue https://travis-ci.org/coreos/etcd/jobs/165927718.

Any updates?

**Comment by dominikh** [comment]
This looks like a simple transient network error to me. I can't tell from my end why they occur. There are no failing requests logged on my end.

Short-term I'd say that retrying the requests is the way to go. Long term I might migrate the service over to the Google cloud.

**Comment by dominikh** [comment]
The honnef.co/go/ endpoint is now being served by Google's network. That should hopefully eliminate the intermittent timeouts.

**Comment by gyuho** [comment]
Thank you! And thanks for the great project!
