### ISSUE TITLE
Simplification for return err is questionable

### ISSUE THREAD

**Issue by m0sth8** [dominikh/go-simple#23]
Hello, I think this rule:

```
Don't write

if err != nil {
  return err
}
return nil
write

return err
instead
```

is questionable, because of this situation:
https://play.golang.org/p/95TqfwDaxQ

**Comment by dominikh** [comment]
I'm not sure what the linked-to playground is supposed to demonstrate. It's not triggering any of gosimple's rules.

**Comment by m0sth8** [comment]
According to the documentation there (https://github.com/dominikh/go-simple/blob/master/README.md#checks), one of your checks gives the advice to replace:

```
if err != nil {
  return err
}
return nil
```

with

```
return err
```

The example I gave in the first comment shows that sometimes this rule brakes program logic.

**Comment by dominikh** [comment]
Since your example doesn't actually trigger any gosimple rules, it doesn't serve as an example of something broken. Please write an example that actually incorrectly triggers a gosimple rule.

But if I am deciphering your intent correctly, this is about #14 which has since been fixed.

**Comment by m0sth8** [comment]
Oh, I see. So this issue might be converted to:
Please remove this phrase from README.md:

```
Don't write

if err != nil {
  return err
}
return nil
write

return err
instead
```

Thank you for your linters.

**Comment by dominikh** [comment]
The README is just a summary of the different rules, and the examples apply to 99% of code out there. It's not a strict "what to do" guide as such, but just an explanation of the kinds of things the tool will look for. In particular, the README assumes that you know Go, that you don't blindly make changes and that you test your changes.

Furthermore, we can't outright remove the phrase without replacing it with something else, and given the reasoning above, I don't think there's a better replacement. As long as the tool itself doesn't make wrong suggestions, there's no bug to fix here.

**Comment by dmitshur** [comment]
Maybe adding a "In some situations," prefix before "Don't write ..." would help?

But the question is, does that apply to all other entries there too? Or are all other entries applicable in all situations?

If all rules are equally dependent on context, then maybe change the header from:

> Gosimple makes the following recommendations for avoiding unsimple constructs:

To something like "Gosimple makes the following recommendations, in situations where it's possible to do so safely, for avoiding unsimple constructs:".

I agree the current phrasing makes it sound a little too much like "_always_ do this whenever you see this exact pattern in code", which is clearly not true and not what go-simple does.
