### ISSUE TITLE
undefined: types.IdenticalIgnoreTags

### ISSUE THREAD

**Issue by gyuho** [dominikh/go-simple#24]
We are building with Go tip, but keep getting this error

```
../../../honnef.co/go/simple/lint18.go:7: undefined: types.IdenticalIgnoreTags
```

https://github.com/dominikh/go-simple/blob/master/lint18.go

Any idea? Thanks!

**Comment by dmitshur** [comment]
I think it's because https://go-review.googlesource.com/24190 isn't merged into tip yet. This will be resolved when it is.

**Comment by dmitshur** [comment]
> Because [CL 24190](https://go-review.googlesource.com/24190) isn't merged into tip yet. This will be resolved when it is.

Or, likely sooner. :P _*shurcooL uses his predictive powers*_

In 3, 2, 1... -30 minutes. Kinda close.

**Comment by dominikh** [comment]
Sorry about the breakage.

@shurcooL Your clock is running too fast.

**Comment by dmitshur** [comment]
It was optimistically eager. :)

**Comment by gyuho** [comment]
@dominikh @shurcooL Ok got it. We will just wait.

Thanks all!
