### ISSUE TITLE
Suggest simplification of fallthrough switch case statements

### ISSUE THREAD

**Issue by aultimus** [dominikh/go-simple#26]
Do you consider the following simplification (A->B) of switch statements to be within the scope of gosimple?

Thanks,
Matt

A:

```
package main

func f(x int, c chan struct{}) {
    switch x {
    case 1:
        fallthrough
    case 2:
        fallthrough
    case 3:
        c <- struct{}{}
    }

}

func main() {
    c := make(chan struct{})
    go f(3, c)
    <-c
}
```

B:

```
package main

func f(x int, c chan struct{}) {
    switch x {
    case 1, 2, 3:
        c <- struct{}{}
    }

}

func main() {
    c := make(chan struct{})
    go f(3, c)
    <-c
}
```

**Comment by dominikh** [comment]
My first reaction would be "yes". But I would need to run it against my large real world corpus to make sure there aren't valid situations in which the first variant is preferable.

**Comment by aultimus** [comment]
OK, thank you, I'll open up a PR soon then :)

**Comment by bradleyfalzon** [comment]
Depending on exactly what you are looking at suggesting, we do things similar to the following where we've added docs to each `fallthrough`: https://github.com/golang/go/blob/897c0ebf61daaaf9c02be577f1afcb2c67ff3ed5/src/cmd/compile/internal/arm/ssa.go#L605-L620 which we wouldn't want to see optimised.

**Comment by aultimus** [comment]
Can potentially discriminate between case 1 and 2

```
func f(x int, c chan struct{}) {
    switch x {
    case 1:
        // comment
        fallthrough
    case 2:
        fallthrough
    case 3:
        c <- struct{}{}
    }
}
```

**Comment by dominikh** [comment]
@aultimus Do you still intend to work on this?
