### ISSUE TITLE
undeclared name warnings for swig defined names

### ISSUE THREAD

**Issue by aultimus** [dominikh/go-simple#30]
A recent update seems to produce warnings of 'undeclared name' for names, used in go which are defined in c via swig

**Comment by dominikh** [comment]
Previously, gosimple silently ignored type checking errors and worked with what information it had, leading to incomplete results. Its new architecture, however, requires working on well typed packages, and packages that don't type check are skipped entirely, and loudly.

We do support cgo (assuming the necessary headers for compilation are available). I do not know if we support SWIG, or how SWIG integration in Go works in the first place. Does SWIG require integration with the toolchain? In that case, go/loader, and by extension gosimple, do not support it, with no plans to support it, either.

**Comment by dmitshur** [comment]
> We do support cgo (assuming the necessary headers for compilation are available).

In what way are they supported?

Does it require the Cgo package to be installed? Would it help if they were installed, or are Cgo packages always built from source?

**Comment by dominikh** [comment]
gosimple, and all tools based on my `lint` package, do not rely on installed packages anymore. For cgo, `go/loader` applies the same logic that the Go tool does: it executes `go tool cgo` and works with the rewritten files.

**Comment by dominikh** [comment]
Going to close this issue because of lack of feedback.
