### ISSUE TITLE
suggest copy() for sliding elements

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-simple#31]
Say we want to slide `n` bytes at `offset` of `bs` to the beginning (or to any other offset, really):

```
for i := 0; i < n; i++ {
        bs[i] = bs[offset+i]
}
```

The same can be rewritten to:

```
copy(bs[:n], bs[offset:offset+n])
```

Or a little simpler, since the amount copied is the minimum of the two lengths:

```
copy(bs[:n], bs[offset:])
```

**Comment by dominikh** [comment]
@shurcooL Do you have an opinion on this?

**Comment by dmitshur** [comment]
After thinking about it for a few minutes, the change suggestion itself seems good.

I haven't benchmarked it, but I suspect there's a good chance it's either faster, or the same.

It looks simpler, shorter. Not obscure. Not difficult to understand.

I don't know how easy/viable it is to detect when it can be made, without false positives. I haven't verified if it's still applicable if there's overlap.

It seems like a simplification that's easy to miss, so if it can be reported by a tool automatically, and there are (or will be) occurrences in real world, its value goes up.
