### ISSUE TITLE
Suggests !!someBool instead of someBool

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-simple#33]
```
package foo

func Foo(ok bool) {
        if !ok == false {
        }
}
```

```
 $ gosimple f.go
f.go:4:5: should omit comparison to bool constant, can be simplified to !!ok (S1002)
```

I must admit this is a very nasty piece of code, but nevertheless the suggestion should be simplified.

**Comment by dmitshur** [comment]
Is it okay if it makes two simplification suggestions, instead of "squashing" them into one?

I.e., first change `!ok == false` to `!!ok`, then `!!ok` to `ok`.

**Comment by mvdan** [comment]
I think it should squash them, unless it's very hard to do so.

**Comment by dominikh** [comment]
I agree, we shouldn't make a suggestion that is as bad as the original, and it should be simple enough to fix, for the common cases.
