### ISSUE TITLE
Comparison with gofmt -s

### ISSUE THREAD

**Issue by cespare** [dominikh/go-simple#4]
I notice the docs don't mention `gofmt -s`, but that is the other tool I'm aware of that does accomplishes a similar thing. Is there any overlap between them? Would you consider including all of `gofmt -s`'s checks in go-simple, so I only need to run one tool? :D

In case you're interested, I made a list of the constructs `gofmt -s` simplifies. ([Source here](https://github.com/golang/go/blob/master/src/cmd/gofmt/simplify.go).)
- Remove unnecessary types in literals
- Remove unnecessary `len` in slice expressions: `s[n:len(s)]` -> `s[n:]`
- Remove unnecessary `_` in range statements: `for x, _ := range s` -> `for x := range s` and `for _ = range s` -> `for range s` (I think go-simple does the second already?)
- Remove empty declaration groups (e.g., `const ()`)

**Comment by dominikh** [comment]
Generally: I don't want overlap between tools. go fmt, go vet, golint, and gosimple all target different issues in code, and optimally don't overlap. If `gofmt -s` simplifies `for _ = range x` to `for range x`, then we should probably remove the check from gosimple.

Furthermore, gosimple will not attempt to rewrite code for you. Much like golint, it makes suggestions, and may have false positives (although we try a lot harder than golint at avoiding them).

While `gofmt -s` focuses on syntactic simplification, gosimple, for the most part, looks at larger semantic constructs. So I'm afraid you'll need to run two tools.

**Comment by cespare** [comment]
> Generally: I don't want overlap between tools. go fmt, go vet, golint, and gosimple all target different issues in code, and optimally don't overlap.

I agree with the sentiment, but `gofmt -s` is fairly little-used from what I've seen (it doesn't really do that much stuff, and people don't seem to know about it). It also hasn't really seen any attention or improvements over the years. So in this case, it felt to me like gosimple could be the fleshed-out version of `gofmt -s` I've been waiting for, and supersede it.

> Furthermore, gosimple will not attempt to rewrite code for you. Much like golint, it makes suggestions, and may have false positives

That suits my workflows just fine.

> While gofmt -s focuses on syntactic simplification, gosimple, for the most part, looks at larger semantic constructs.

Looking through the list of checks, I don't see how the simplifications that `gofmt -s` make are different. In particular, all of the following seem to be in the same vein as the `gofmt -s`:
- Don't use `select{}` with a single case. Instead, use a plain
  channel send or receive.
- Don't use `for { select {} }` with a single receive case. Instead,
  use `range` to iterate over the channel.
- Don't compare boolean expressions to the constants `true` or
  `false`. `if x == true` can be written as `if x` instead.
- Don't use `for _ = range x`, use `for range x`
- Don't use `for true { ... }`, use `for { ... }`
- Don't use `if <expr> { return <bool> }; return <bool>`, use `return
  <expr>`, unless the `if` is one in a series of many early returns.
- Don't check if slices, maps or channels are nil before checking
  their length, it's redundant. `len` is defined as zero for those nil
  values.

**Comment by dominikh** [comment]
> So in this case, it felt to me like gosimple could be the fleshed-out version of gofmt -s I've been waiting for, and supersede it.

Are there any concrete modifications/additions you would make to `gofmt -s`?

> - Don't use select{} with a single case. Instead, use a plain channel send or receive
> - Don't use for { select {} } with a single receive case. Instead, use range to iterate over the channel
> - Don't use if <expr> { return <bool> }; return <bool>, use return <expr>, unless the if is one in a series of many early returns
> - Don't check if slices, maps or channels are nil before checking their length

The first 3 of those replace entire code constructs with others. They don't just remove superfluous information. And the fourth is a change in logic with equivalent outcome. I don't consider those syntactic changes in nature

> - Don't use for _ = range x, use for range x
> - Don't use for true { ... }, use for { ... }
> - Don't compare boolean expressions to the constants true or false.

Yes, these are syntactic modifications, However I'd intend to remove the first one if `gofmt -s` already takes care of it.

At the moment, I'm leaning towards sleeping on it for a day or two before making my final decision. My goal is having simple code, and I'd love everyone to use `gofmt -s`. If it's really that little used¹, and you can actually suggest real improvements that could be made to it, then I'm willing to consider adding it to gosimple. 

¹: I was disappointed to see that it's disabled by default in gometalinter.

**Comment by dmitshur** [comment]
About `gofmt -s` popularity, I'm just one data point, but I have it enabled in CI in all my repos. I see no reason not to use it, unless you care about preserving compatibility with non-latest releases of Go.

**Comment by kostya-sh** [comment]
One possible reason why `gofmt -s` is not popular is that many developers use `goimports` instead of `gofmt` and goimports doesn't support `-s` option.

I support the idea of adding `gofmt -s` checks to go-simple. gofmt should do formatting. linters (such as golint, vet and gosimple) should point to possible problems or style issues.

BTW, `for x, _ := range s` (but not `for _ = range s`) check exists in both in gofmt and golint.

**Comment by dominikh** [comment]
I've started copying `gofmt -s` into gosimple and I'm not sure if it's a good fit. A significant amount of code isn't simplified, and some files have hundreds of hits. That makes gosimple very spammy.

I'm considering just reporting one line per file, of the kind `should run gofmt -s`. However, that conflicts with @cespare's suggestion that he'd like changes/additions to `gofmt -s`, unless those don't produce as many hits as `gofmt -s` does.

**Comment by dominikh** [comment]
Even that approach is still very noisy, in that it flags a majority of code. In 211553 packages, it flags 37892 files. I don't feel grandiose enough to tell most of the Go world that their code sucks and that they should run `gofmt -s`.

**Comment by kostya-sh** [comment]
What are the constructs that are most frequently flagged?

**Comment by dominikh** [comment]
It looks like a somewhat even mix of `for x, _ := range` and eliding types in composite literals.

**Comment by kostya-sh** [comment]
`for x, _ := range` is already reported by golint.

Suggesting only some of the `gofmt -s` checks could be a good start:
- empty blocks
- `for _ = range` (already done?)
- slice expressions with len

**Comment by cespare** [comment]
> I don't feel grandiose enough to tell most of the Go world that their code sucks and that they should run `gofmt -s`.

I think you shouldn't feel inhibited! There is a lot of code that does suck.

Here's how I'm feeling about each of `gofmt -s`'s features after reading this thread:
- Remove unnecessary types in literals

I still like this change (I would want to always fix it if it happens in my code). Up to you.
- Remove unnecessary len in slice expressions: s[n:len(s)] -> s[n:]

This seems like a good fit for gosimple. I think it's worth doing.
- Remove unnecessary _ in range statements: `for x, _ := range s` -> `for x := range s` and `for _ = range s` -> `for range s`

I see that golint already flags the first kind and is unwilling to flag the second (which gosimple handles), so the current situation seems fine to me.
- Remove empty declaration groups (e.g., const ())

This seems like it would be in scope for gosimple, but how often does it happen? (Can you report from your corpus?) Maybe not worth including because it's presumably rare.

**Comment by dominikh** [comment]
> I think you shouldn't feel inhibited! There is a lot of code that does suck.

True; but I think in this instance it's more a case of personal opinion – a lot of people probably don't mind the more explicit literals and that's fine. It matched _a lot_ of code.

> Can you report from your corpus?

```
csearch "^(var|const|type) \(\)" | wc -l        
635
```

104 of those are in a single, auto-generated file. The rest is either auto-generated, or years old garbage code.

Not worth adding in my opinion.

I guess we'll add the check for unnecessary length in slicing operations only.
