### ISSUE TITLE
Multiple package arguments

### ISSUE THREAD

**Issue by cespare** [dominikh/go-simple#5]
I'm curious why gosimple can't be used with multiple package arguments. (Or rather, why multiple arguments are interpreted as filenames.) This is useful with `go list` (e.g., `gosimple $(go list ./... | grep -v vendor)`.)

(Also, I noticed that `unused` works this way.)

**Comment by cespare** [comment]
I guess it's for consistency with golint?

**Comment by dominikh** [comment]
Not so much consistency, and more a case of "we forked golint and didn't tweak its behaviour". Will fix.

**Comment by dominikh** [comment]
Fixed in https://github.com/dominikh/go-lint/commit/a7d2b2c0fec5c0e7057416314105e7d82cd1424c
